name: CI

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Cloning repo 1
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to dokku 1
        uses: dokku/github-action@master
        with:
          git_remote_url: 'ssh://dokku@astro31.ru/pgs02'
          ssh_private_key: ${{ secrets.TIMEWEB_ID_RSA }}
          git_push_flags: '--force'

      - name: Cloning repo 2
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to dokku 2
        uses: dokku/github-action@master
        with:
          git_remote_url: 'ssh://dokku@v--moskve.ru/pgs03'
          ssh_private_key: ${{ secrets.TIMEWEB_ID_RSA }}
          git_push_flags: '--force'
