name: CI

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Cloning repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to dokku
        uses: dokku/github-action@master
        with:
          git_remote_url: 'ssh://dokku@212.113.123.59:22/pgs02'
          ssh_private_key: ${{ secrets.TIMEWEB_ID_RSA }}
          git_push_flags: '--force'
